apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - rhoai/subscription.yaml
  - connectivity-link/subscription.yaml
  - cert-manager/subscription.yaml
  - service-mesh/subscription.yaml
  - leader-worker-set/subscription.yaml
  - gpu/nfd-subscription.yaml
  - gpu/nvidia-subscription.yaml
  - devspaces/subscription.yaml
  - coo/subscription.yaml
  - opentelemetry/subscription.yaml
  - tempo/subscription.yaml
