apiVersion: perses.dev/v1alpha2
kind: PersesDatasource
metadata:
  name: cluster-prometheus-datasource
  namespace: redhat-ods-monitoring
spec:
  client:
    tls:
      caCert:
        certPath: service-ca.crt
        name: prometheus-web-tls-ca
        namespace: redhat-ods-monitoring
        type: configmap
      enable: true
  config:
    default: true
    display:
      description: Cluster Prometheus - provides platform and cluster metrics
      name: Cluster Prometheus
    plugin:
      kind: PrometheusDatasource
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: https://thanos-querier.openshift-monitoring.svc:9092
        scrapeInterval: 30s
