apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSSubscription
metadata:
  name: devspaces-subscription
  namespace: models-as-a-service
spec:
  modelRefs:
    - name: qwen3-8b
      namespace: models-as-a-service
      tokenRateLimits:
        - limit: 50000
          window: "1h"
  owner:
    groups:
      - name: devspaces-users
  priority: 10
  tokenMetadata:
    costCenter: "engineering-tools"
