apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kuadrant/kuadrant.yaml
  - monitoring/user-workload-monitoring.yaml
  - gateway/gateway-class.yaml
  - gateway/gateway-resources.yaml
